;/*FB_PKG_DELIM*/

__d("FDSDocumentFilled16Icon",["cr:13997"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:13997")}),98);
__d("FDSMapFilled20Icon",["cr:15245"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:15245")}),98);
__d("FDSMapFilled20PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("645715"),20);b=a;g["default"]=b}),98);
__d("FDSPhotoAddFilled24Icon",["cr:15400"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:15400")}),98);
__d("FDSUndoFilled16Icon",["cr:15840"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:15840")}),98);
__d("FDSWatchTvFilled20Icon",["cr:15866"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:15866")}),98);
__d("FDSWatchTvFilled20PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("607169"),20);b=a;g["default"]=b}),98);
__d("GroupsCometAdminActivityLogItemSeeDetailsDialogQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="9407658966029088"}),null);
__d("MessengerSidebarClickEventFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("2305");b=d("FalcoLoggerInternal").create("messenger_sidebar_click_event",a);e=b;g["default"]=e}),98);
__d("MessengerSidebarConversionClickEventFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("2306");b=d("FalcoLoggerInternal").create("messenger_sidebar_conversion_click_event",a);e=b;g["default"]=e}),98);
__d("MessengerSidebarImpressionEventFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("2307");b=d("FalcoLoggerInternal").create("messenger_sidebar_impression_event",a);e=b;g["default"]=e}),98);
__d("MessengerSidebarClickImpressionEventsLoggerImpl",["MessengerClickImpressionEventsLoggerUtils","MessengerSidebarClickEventFalcoEvent","MessengerSidebarConversionClickEventFalcoEvent","MessengerSidebarImpressionEventFalcoEvent"],(function(a,b,c,d,e,f,g){"use strict";f={scrollMargin:-33};function a(a){h(a,d("MessengerClickImpressionEventsLoggerUtils").EventTypeEnum.CLICK)}function b(a){h(a,d("MessengerClickImpressionEventsLoggerUtils").EventTypeEnum.CONVERSION)}function e(a){h(a,d("MessengerClickImpressionEventsLoggerUtils").EventTypeEnum.IMPRESSION)}function h(a,b){var e=a.id,f=a.isOnline,g=a.position,h=a.storyIds,i=a.surface;a=a.targetType;var j;if(b===d("MessengerClickImpressionEventsLoggerUtils").EventTypeEnum.CLICK)j="single_click";else if(b===d("MessengerClickImpressionEventsLoggerUtils").EventTypeEnum.CONVERSION)j="single_click";else if(b===d("MessengerClickImpressionEventsLoggerUtils").EventTypeEnum.IMPRESSION)j="vpvd_impression";else return;var k={event_type:j,surface:{entry_point:i.entry_point,major_surface:i.major_surface,minor_surface:i.minor_surface},target:{ranking:{absolute_position:g!=null?g.toString():"-1"},type:a,user:{id:e}}};f!=null&&(k=babelHelpers["extends"]({},k,{target:babelHelpers["extends"]({},k.target,{presence:{status:f?1:0}})}));if((h==null?void 0:h.firstCardId)!=null&&(h==null?void 0:h.bucketId)!=null){j=atob(h.firstCardId);i=null;j!=null&&j.includes("S:_ISC:")&&(i=j.split("S:_ISC:")[1]);k=babelHelpers["extends"]({},k,{target:babelHelpers["extends"]({},k.target,{story:{bucket_id:(g=h.bucketId)!=null?g:null,first_card_id:(a=i)!=null?a:null}})})}b===d("MessengerClickImpressionEventsLoggerUtils").EventTypeEnum.CLICK?c("MessengerSidebarClickEventFalcoEvent").log(function(){return k}):b===d("MessengerClickImpressionEventsLoggerUtils").EventTypeEnum.CONVERSION?c("MessengerSidebarConversionClickEventFalcoEvent").log(function(){return k}):b===d("MessengerClickImpressionEventsLoggerUtils").EventTypeEnum.IMPRESSION&&c("MessengerSidebarImpressionEventFalcoEvent").log(function(){return k})}g.IMPRESSION_LOG_OPTIONS=f;g.logClickEvent=a;g.logConversionClickEvent=b;g.logImpressionEvent=e}),98);
__d("WebBloksURLUtils",[],(function(a,b,c,d,e,f){"use strict";function a(a,b){b=new RegExp("[?&]"+b.join("(?:=[^&]*)?|[?&]")+"(?:=[^&]*)?","gi");var c=a.indexOf("?")!==-1?"&":"?";a=a.replace(b,"").replace(/&$/,"");return a.indexOf("?")===-1&&a.indexOf("&")!==-1?a.replace("&","?"):a.replace("?&",c)}function b(a){if(/^(fb|https?|intent):\/\//i.test(a))return a;if(/^mailto:/i.test(a))return a;var b=window.location.protocol+"//"+window.location.hostname,c=a;a.charAt(0)==="/"&&(c=a.substr(1));return b+"/"+c}function c(a,b){b===void 0&&(b=!1);var c=window.location.href;b?window.open(a,"_blank"):a===c?window.location.reload():window.location.href=a}function d(a,b){var c=a.split("?")[0];a=a.split("?")[1]||"";a=g(a);a=babelHelpers["extends"]({},a,b);b=Object.entries(a).map(function(a){var b=a[0];a=a[1];return typeof a==="string"&&a.length===0?b:encodeURIComponent(b)+"="+encodeURIComponent(a)}).join("&");return c+"?"+b}function g(a){var b={};a&&a.split("&").forEach(function(a){a=a.split("=");var c=a[0];a=a[1];b[decodeURIComponent(c)]=decodeURIComponent(a===void 0?"":a)});return b}f.removeQueryParams=a;f.qualify=b;f.openURL=c;f.addQueryParamsToUrl=d}),66);
__d("WebGraphQLLegacyHelper",["invariant"],(function(a,b,c,d,e,f,g,h){"use strict";function a(a){var b=a.controller,c=a.docID,d=a.queryID,e=a.variables;a=a.legacyResponseFormat;c!=d&&(c||d)!=null||h(0,5819,c,d);b=b.getURIBuilder();d?b.setFBID("query_id",d):b.setFBID("doc_id",c);a&&b.setBool("legacy_response_format",!0);e&&b.setString("variables",JSON.stringify(e));return b.getURI()}g.getURI=a}),98);